package com.SoMessThat.sys.vo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_department
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DepartmentVo extends BaseVo implements Serializable {
    /**
     * Database Column Remarks:
     *   Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   单位名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   部门性质
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   成立时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.registration_time
     *
     * @mbg.generated
     */
    private Date registrationTime;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * Database Column Remarks:
     *   部门信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     * Database Column Remarks:
     *   职责
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * Database Column Remarks:
     *   简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * Database Column Remarks:
     *   其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.other
     *
     * @mbg.generated
     */
    private String other;

    /**
     * Database Column Remarks:
     *   负责人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.master_name
     *
     * @mbg.generated
     */
    private String masterName;

    /**
     * Database Column Remarks:
     *   联系人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.master_tel
     *
     * @mbg.generated
     */
    private String masterTel;

    /**
     * Database Column Remarks:
     *   辖区Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.area_id
     *
     * @mbg.generated
     */
    private Long areaId;

    /**
     * Database Column Remarks:
     *   上级编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.parent_code
     *
     * @mbg.generated
     */
    private String parentCode;

    /**
     * Database Column Remarks:
     *   路劲
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.parent_path
     *
     * @mbg.generated
     */
    private String parentPath;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_department.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.id
     *
     * @return the value of sys_department.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.id
     *
     * @param id the value for sys_department.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.name
     *
     * @return the value of sys_department.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.name
     *
     * @param name the value for sys_department.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.code
     *
     * @return the value of sys_department.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.code
     *
     * @param code the value for sys_department.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.type
     *
     * @return the value of sys_department.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.type
     *
     * @param type the value for sys_department.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.registration_time
     *
     * @return the value of sys_department.registration_time
     *
     * @mbg.generated
     */
    public Date getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.registration_time
     *
     * @param registrationTime the value for sys_department.registration_time
     *
     * @mbg.generated
     */
    public void setRegistrationTime(Date registrationTime) {
        this.registrationTime = registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.position
     *
     * @return the value of sys_department.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.position
     *
     * @param position the value for sys_department.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.info
     *
     * @return the value of sys_department.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.info
     *
     * @param info the value for sys_department.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.duty
     *
     * @return the value of sys_department.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.duty
     *
     * @param duty the value for sys_department.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.introduction
     *
     * @return the value of sys_department.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.introduction
     *
     * @param introduction the value for sys_department.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.other
     *
     * @return the value of sys_department.other
     *
     * @mbg.generated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.other
     *
     * @param other the value for sys_department.other
     *
     * @mbg.generated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.master_name
     *
     * @return the value of sys_department.master_name
     *
     * @mbg.generated
     */
    public String getMasterName() {
        return masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.master_name
     *
     * @param masterName the value for sys_department.master_name
     *
     * @mbg.generated
     */
    public void setMasterName(String masterName) {
        this.masterName = masterName == null ? null : masterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.master_tel
     *
     * @return the value of sys_department.master_tel
     *
     * @mbg.generated
     */
    public String getMasterTel() {
        return masterTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.master_tel
     *
     * @param masterTel the value for sys_department.master_tel
     *
     * @mbg.generated
     */
    public void setMasterTel(String masterTel) {
        this.masterTel = masterTel == null ? null : masterTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.area_id
     *
     * @return the value of sys_department.area_id
     *
     * @mbg.generated
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.area_id
     *
     * @param areaId the value for sys_department.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.parent_code
     *
     * @return the value of sys_department.parent_code
     *
     * @mbg.generated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.parent_code
     *
     * @param parentCode the value for sys_department.parent_code
     *
     * @mbg.generated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.parent_path
     *
     * @return the value of sys_department.parent_path
     *
     * @mbg.generated
     */
    public String getParentPath() {
        return parentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.parent_path
     *
     * @param parentPath the value for sys_department.parent_path
     *
     * @mbg.generated
     */
    public void setParentPath(String parentPath) {
        this.parentPath = parentPath == null ? null : parentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.create_time
     *
     * @return the value of sys_department.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.create_time
     *
     * @param createTime the value for sys_department.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.update_time
     *
     * @return the value of sys_department.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.update_time
     *
     * @param updateTime the value for sys_department.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.status
     *
     * @return the value of sys_department.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.status
     *
     * @param status the value for sys_department.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", registrationTime=").append(registrationTime);
        sb.append(", position=").append(position);
        sb.append(", info=").append(info);
        sb.append(", duty=").append(duty);
        sb.append(", introduction=").append(introduction);
        sb.append(", other=").append(other);
        sb.append(", masterName=").append(masterName);
        sb.append(", masterTel=").append(masterTel);
        sb.append(", areaId=").append(areaId);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", parentPath=").append(parentPath);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}