package com.SoMessThat.sys.vo;

import java.io.Serializable;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ccop_res_service_api
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TreeVo extends BaseVo implements Serializable {
    
	/**
	 *  
	 */
	private static final long serialVersionUID = 1L;

	/**
     *   主键code
     */
    private String code;

    /**
     *   名称
     */
    private String name;

    /**
     *   上级部门id
     */
    private String parentCode;

    /**
     *   子部门节点
     */
    private List<TreeVo> node;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<TreeVo> getNode() {
		return node;
	}

	public void setNode(List<TreeVo> node) {
		this.node = node;
	}

	public String getParentCode() {
		return parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}