package com.SoMessThat.sys.mapper;

import java.util.List;
import java.util.Map;

import com.SoMessThat.sys.domain.Right;
import com.SoMessThat.sys.vo.RightVo;
import com.SoMessThat.sys.vo.TreeVo;

public interface RightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    int insertSelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    Right selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Right record);

	List<RightVo> queryRight(RightVo vo);

	List<RightVo> findRightTreeByRole(Map<String, Long> map);

	List<TreeVo> queryRightTree();

	RightVo findRightByCode(String code);

	int delRightIds(Map<String, Object> param);

	int addRightIds(Map<String, Object> param);
}