package com.SoMessThat.sys.mapper;

import java.util.List;
import java.util.Map;

import com.SoMessThat.sys.domain.User;
import com.SoMessThat.sys.vo.PowerDTO;
import com.SoMessThat.sys.vo.UserVo;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

	List<UserVo> queryUser(UserVo vo);

	List<UserVo> findRoleList(UserVo user);

	int delRoleIds(Map<String, Object> param);

	int addRoleIds(Map<String, Object> param);

	List<PowerDTO> selectPowerRootByUserID(Long id);
}