package com.SoMessThat.sys.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_right
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Right extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   父级编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.pcode
     *
     * @mbg.generated
     */
    private Long pcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   URL地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   资源类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   应用状态(是否上下架)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.application_status
     *
     * @mbg.generated
     */
    private String applicationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right.orders
     *
     * @mbg.generated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.id
     *
     * @return the value of sys_right.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.id
     *
     * @param id the value for sys_right.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.name
     *
     * @return the value of sys_right.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.name
     *
     * @param name the value for sys_right.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.code
     *
     * @return the value of sys_right.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.code
     *
     * @param code the value for sys_right.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.pcode
     *
     * @return the value of sys_right.pcode
     *
     * @mbg.generated
     */
    public Long getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.pcode
     *
     * @param pcode the value for sys_right.pcode
     *
     * @mbg.generated
     */
    public void setPcode(Long pcode) {
        this.pcode = pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.update_time
     *
     * @return the value of sys_right.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.update_time
     *
     * @param updateTime the value for sys_right.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.description
     *
     * @return the value of sys_right.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.description
     *
     * @param description the value for sys_right.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.url
     *
     * @return the value of sys_right.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.url
     *
     * @param url the value for sys_right.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.icon
     *
     * @return the value of sys_right.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.icon
     *
     * @param icon the value for sys_right.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.type
     *
     * @return the value of sys_right.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.type
     *
     * @param type the value for sys_right.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.status
     *
     * @return the value of sys_right.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.status
     *
     * @param status the value for sys_right.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.application_status
     *
     * @return the value of sys_right.application_status
     *
     * @mbg.generated
     */
    public String getApplicationStatus() {
        return applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.application_status
     *
     * @param applicationStatus the value for sys_right.application_status
     *
     * @mbg.generated
     */
    public void setApplicationStatus(String applicationStatus) {
        this.applicationStatus = applicationStatus == null ? null : applicationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.path
     *
     * @return the value of sys_right.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.path
     *
     * @param path the value for sys_right.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right.orders
     *
     * @return the value of sys_right.orders
     *
     * @mbg.generated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right.orders
     *
     * @param orders the value for sys_right.orders
     *
     * @mbg.generated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", pcode=").append(pcode);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", description=").append(description);
        sb.append(", url=").append(url);
        sb.append(", icon=").append(icon);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", applicationStatus=").append(applicationStatus);
        sb.append(", path=").append(path);
        sb.append(", orders=").append(orders);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}